highlander_says_api:
  path: /highlander-says-api/{treshold<\d+>?50}
  controller: App\Controller\WeatherController::highlanderSaysApi

highlander_says:
  path: /highlander-says/{treshold<\d+>?}
  controller: App\Controller\WeatherController::highlanderSays

highlander_says_guess:
  path: /highlander-says/{guess}
  controller: App\Controller\WeatherController::highlanderSaysGuess

test:
  path: /test
  controller: App\Controller\WeatherController::test
