controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

weather:
  resource: "routes/weather.yaml"
  prefix: "/{_locale}/weather"
  name_prefix: "weather_"
  requirements:
    _locale: "en|es"

home:
  path: "/"
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    permanent: false
    route: "weather_highlander_says_guess"
    guess: "snow"

privacy:
  path: /privacy-policy
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "static/privacy_policy.html.twig"

xss:
  path: /xss
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "static/xss.html.twig"
